Feat/edco 6
pagopa/pagopa-editorial-components pull request #12
Opened 2023-03-21 10:47 UTC by leleOFA

fix style

2023-03-21 14:08 UTC, vito80ba requested changes
Please review carefully in small viewport. Seems there's no padding and the final result is not acceptable
<img width="603" alt="Schermata 2023-03-21 alle 15 06 06" src="https://user-images.githubusercontent.com/1122389/226631969-7ea5a073-4b83-4c1b-8861-f07c057ec286.png">

2023-03-28 07:32 UTC, stratoivandiluccio approved these changes

2023-03-28 07:39 UTC, stratoivandiluccio approved these changes

2023-03-28 08:07 UTC, vito80ba approved these changes

2023-03-28 08:47 UTC, merged