[EDCO-15] Header Component
pagopa/pagopa-editorial-components pull request #13
Opened 2023-03-21 16:43 UTC by mmoio

## Description

Adds [Header Component](https://www.figma.com/file/6Hn7Wxmvg6eCSqsMrIP7VU/CMS---UI-Components-%26-Templates?node-id=1%3A16135&t=nzKrnFmQ3X5gOCVE-1) & related stories

Fixes # (edco-15)

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

- [x] Storybook
- [x] Visual testing

2023-03-21 16:49 UTC, mmoio commented
Note that the dropdown and mobile designs are currently missing. The dark theme is also missing but I added it by replicating the design of the other components.

2023-03-22 16:35 UTC, stratoivandiluccio commented
> Note that the dropdown and mobile designs are currently missing. The dark theme is also missing but I added it by replicating the design of the other components.

I see some update on Figma about the Header Component. I think now you have more elements to work on.

https://www.figma.com/file/6Hn7Wxmvg6eCSqsMrIP7VU/CMS---UI-Components-%26-Templates?node-id=1084-71992&t=qWePooSLePxT4gGx-0

2023-03-30 09:32 UTC, mmoio commented
Added a default mobile and desktop Dropdown item in addition to accepting any jsx element and refactored the DialogBubble as a separate component

2023-03-30 10:36 UTC, vito80ba requested changes
Some considerations and tuning:
- the name of website must be in bold (font-weight 700)
- increase vertical padding of the main _div_
- increase vertical padding within the items of submenu

2023-03-30 10:42 UTC, stratoivandiluccio commented on src/components/Ctas.tsx
> +
Please, let's use the `Generic` type exported from 'src/types/components' instead `JSX.Element`

2023-03-30 10:46 UTC, stratoivandiluccio commented on src/components/Ctas.tsx
> +const isButtonProps = (button: CtaButton): button is CtaButtonProps => {
I defined a generic function utility with the same purpose in 'src/utils'.

2023-03-30 13:49 UTC, stratoivandiluccio approved these changes

2023-03-31 07:40 UTC, merged