Feat/edco 6
pagopa/pagopa-editorial-components pull request #7
Opened 2023-03-17 09:21 UTC by leleOFA

2023-03-17 09:35 UTC, mmoio requested changes

2023-03-17 09:35 UTC, mmoio commented on src/stories/Feature/Feature.stories.tsx
You should remove this file if all of its stories are in the dark.stories.tsx and light.stories.tsx

2023-03-17 09:35 UTC, mmoio commented on src/stories/Feature/dark.stories.tsx
> +  /* 👇 The title prop is optional.
Remove this comment

2023-03-17 09:35 UTC, mmoio commented on src/stories/Feature/dark.stories.tsx
> +  title: 'Feature',
Title should be 'Feature/dark'

2023-03-17 09:35 UTC, mmoio commented on src/stories/Feature/light.stories.tsx
> +  /* 👇 The title prop is optional.
Remove this comment

2023-03-17 09:35 UTC, mmoio commented on src/stories/Feature/light.stories.tsx
> +  title: 'Feature',
Title should be 'Feature/light'

2023-03-17 15:35 UTC, leleOFA commented on src/stories/Feature/Feature.stories.tsx
do it

2023-03-17 15:35 UTC, leleOFA commented on src/stories/Feature/dark.stories.tsx
> +  /* 👇 The title prop is optional.
do it

2023-03-17 15:35 UTC, leleOFA commented on src/stories/Feature/light.stories.tsx
> +  /* 👇 The title prop is optional.
do it

2023-03-17 16:41 UTC, mmoio approved these changes
LGTM

2023-03-20 08:51 UTC, vito80ba approved these changes

2023-03-20 10:05 UTC, merged